language: android
sudo: required
jdk: oraclejdk8
env:
  global:
  - ANDROID_API_LEVEL = 28
  - ANDROID_BUILD_TOOLS_VERSION = 28.0.2
android:
  components:
  - tools
  - platform-tools
  - build-tools-$ANDROID_BUILD_TOOLS_VERSION
  - android - $ANDROID_API_LEVEL
  - extra-google-google_play_services
  - extra-google-m2repository
  - addon-google_apis-google-$ANDROID_API_LEVEL
  licences:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.android/build-cache"
script:
- "./gradlew assembleRelease"
before_install:
- openssl aes-256-cbc -K $encrypted_c1bc0e36afa7_key -iv $encrypted_c1bc0e36afa7_iv -in gnsstest.jks.enc -out gnsstest.jks -d
- yes | sdkmanager "platforms;android-28"
- yes | sdkmanager "build-tools;27.0.3"
- yes | sdkmanager "build-tools;28.0.2"
- chmod +x gradlew
before_deploy:
- cp $TRAVIS_BUILD_DIR/gnsstest.jks $HOME
- cd app/build/outputs/apk/release/
- jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore $HOME/gnsstest.jks -storepass $KEYSTORE_PWD -keypass $KEY_PWD app-release-unsigned.apk $KEY_ALIAS
- jarsigner -verify app-release-unsigned.apk
- "${ANDROID_HOME}/build-tools/28.0.2/zipalign -v 4 app-release-unsigned.apk GNSSTest.apk"
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: OgqXs3M9aTxN2v+5YSLPvTRSLNPCaQ0TVDeVJxmCf0jU7gctOSmmRNE2pWnz7ozZVGDI89LxOmBzz9HaOnubZ8Fj9B2RKyGfN88KOE5WjAdNCgyXTY5VzPZ3yWlXOA7rQOLyKIJ1gCHxMaH2k3XiQ0CBuqj8ct+DUiG/0HWoV0s7iFvbpDT1H0aEV7eU/ghf10UardMGOtodpKtZyohpITlNG90RglBwX5dM1CUIxFTsR7lF957J/TDYAvVa+AlnuvD1DrAQXhURTH92af5VfGkZeEhDeuTsU6gGBdnHUoKEo0LKDL8Jez+aSskhSxJ2D17JMV8xFagxLUb6yFzpoersx3MQVwwtAKaQErcS00v9LbSoAxc1P8LSciFTIW6dht2MCBGpi7stDSbNLFQhxtVnODtqqOu6bLcZHa7Eoz9yjdkzcjb6sHgACXcuqGy9cwMlMZVOgwb5HbvP5E/W9qwl0szvKxbMyB5ri0/XGmXy40YLKWzX6aKq8Eliac/dumXuLA8pUUUy1LrBqN+/8k+uSVvyJwcv+kBxdpVlWf1PQaz6ZEg96N7czJxVuDQvS0JYcar5Uutr6ZcQHYSqyZBS+GV/OXuFn88pmUbzZx4WI8/K2WfHQ+s2MY4GEMKZ7MRF2nffxmpVWfHJdy3t2O7bRU/FOKPB+5XLnyxDg6U=
  file: GNSSTest.apk
  on:
    tags: true
