language: android
sudo: required
jdk: oraclejdk8
env:
  global:
  - ANDROID_API_LEVEL = 28
  - ANDROID_BUILD_TOOLS_VERSION = 28.0.2
android:
  components:
  - tools
  - platform-tools
  - build-tools-$ANDROID_BUILD_TOOLS_VERSION
  - android - $ANDROID_API_LEVEL
  - extra-google-google_play_services
  - extra-google-m2repository
  - addon-google_apis-google-$ANDROID_API_LEVEL
  licences:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.android/build-cache"
script:
- "./gradlew assembleRelease"
before_install:
- openssl aes-256-cbc -K $encrypted_1a17ea543043_key -iv $encrypted_1a17ea543043_iv -in gnsstest.jks.enc -out gnsstest.jks -d
- yes | sdkmanager "platforms;android-28"
- yes | sdkmanager "build-tools;27.0.3"
- yes | sdkmanager "build-tools;28.0.2"
- chmod +x gradlew
before_deploy:
- cp $TRAVIS_BUILD_DIR/gnsstest.jks $HOME
- cd app/build/outputs/apk/release/
- jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore $HOME/gnsstest.jks -storepass $KEYSTORE_PWD -keypass $KEY_PWD app-release-unsigned.apk $KEY_ALIAS
- jarsigner -verify app-release-unsigned.apk
- "${ANDROID_HOME}/build-tools/28.0.2/zipalign -v 4 app-release-unsigned.apk GNSSTest.apk"
deploy:
  provider: releases
  skip_cleanup: true
  api_key: ${GITHUB_TOKEN}
  file: GNSSTest.apk
  on:
    tags: true

